// Generated by CoffeeScript 1.7.1
var app, express, http, httpServer;

express = require('express');

http = require('http');

app = express();

app.set('views', __dirname + '/public');

app.set('view engine', 'ejs');

app.use(express.cookieParser());

app.use(express.bodyParser());

app.use(express.errorHandler({
  dumpExceptions: true,
  showStack: true
}));

app.use(express.session({
  secret: 'data fish secret'
}));

app.engine('html', require('ejs').renderFile);

app.use(app.router);

app.use('/img', express["static"](__dirname + '/img'));

app.use('/font-awesome', express["static"](__dirname + '/font-awesome'));

app.use('/js', express["static"](__dirname + '/js'));

app.use('/css', express["static"](__dirname + '/css'));

app.use('/static', express["static"](__dirname + '/public'));

httpServer = http.createServer(app).listen(8081);

console.log('Server running at http://localhost:8081');

app.get('/', function(req, res) {
  res.render('home.html');
});

app.get('/dashboard', function(req, res) {
  res.render('dash.html');
  
});

app.get('/account', function(req, res) {
  if (req.user != null) {
    return res.render('account.html');
  } else {
    console.log('not logged in');
    return res.redirect('/');
  }
});

app.get('/streamPage', function(req, res) {
  return res.render('stream.html');
});

app.get('/searchPage', function(req, res) {
  return res.render('search.html');
});

app.get('/userPage', function(req, res) {
  return res.render('user.html');
});
