// Generated by CoffeeScript 1.7.1
var LocalStrategy, bcrypt, express, http, secrets, socket;

socket = require('socket.io');

express = require('express');

LocalStrategy = require('passport-local').Strategy;

bcrypt = require('bcrypt');

secrets = require('./secrets.json');

http = require('http');
